name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Ensure devDependencies (like typescript for next.config.ts) are installed
  NPM_CONFIG_PRODUCTION: "false"
  NEXT_PUBLIC_BASE_PATH: "wap.github.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install all deps incl. dev (fixes "Cannot find module 'typescript'")
      - name: Install deps (include dev)
        run: npm ci --include=dev

      - name: Verify TypeScript is present
        run: node -e "console.log('TS:', require.resolve('typescript'))"

      - name: Build (static export happens during build)
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (out/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
